### ISSUE TITLE
update DISCOtoolkit_py failure

### ISSUE THREAD

**Issue by Dacy34** [JinmiaoChenLab/DISCOtoolkit_py#1]
Hi Mengwei，
Thank you very much for porting DISCO to python! I want to try to use disco_py, but I installed version 1.0.4 through pip, and the download of this version will fail. I tried to install version 1.0.7 locally and online, but I got an error. I don't know what to do.
Best
Mengtian
![1684208244755](https://github.com/JinmiaoChenLab/DISCOtoolkit_py/assets/124675082/ee0fa9bd-9aa1-4e0c-9951-a8120e24586e)
![1684208174314](https://github.com/JinmiaoChenLab/DISCOtoolkit_py/assets/124675082/a006f965-49ca-4b2e-a577-8928fb4cc95d)
![1684208219772](https://github.com/JinmiaoChenLab/DISCOtoolkit_py/assets/124675082/a93822bf-fb4a-44f6-aa91-24087a2d1e09)

**Comment by uddamvathanak** [comment]
Hi Mengtian,

Thank you so much for trying the discotoolkit python version. Sorry for the inconvenient as I'm currently working on it so there bound to be some error. I have updated the pip for version 1.0.7 and please give it a try again and see if the error persist.

**Comment by uddamvathanak** [comment]
Hi Mengtian,

Thank you so much for trying the discotoolkit python version. Sorry for the inconvenient as I'm currently working on it so there bound to be some error. I have updated the pip for version 1.0.7 and please give it a try again and see if the error persist.

Thanks,

Rom Uddamvathanak

**Comment by Dacy34** [comment]
Hi Uddamvathanak,

Thank you for your positive reply! I have upgraded to version 1.0.8, but I seem to have encountered new problems. I reinstalled openSSL to eliminate the cause of my own system. The error report is shown in the figure below. I tried other code to test the network download (the next figure), and it didn't seem to be a problem. Moreover, the upgrade process is a bit tortuous, and it was finally installed manually after pypi downloaded the whl file. It seems that the pip mirror website has not updated version 1.0.8. Looking forward to your reply.

Best,
Mengtian

![1684294288611](https://github.com/JinmiaoChenLab/DISCOtoolkit_py/assets/124675082/c2ff8c5e-ae21-4d51-ab7f-2778c8c93602)
![1684294633793](https://github.com/JinmiaoChenLab/DISCOtoolkit_py/assets/124675082/68259d0c-da95-4e99-8b49-0d44fd5b0e77)

**Comment by uddamvathanak** [comment]
Hi Mengtian,

I have update the version of discotoolkit to the pypi distribution which you can install easily using pip -U install discotoolkit.

I would suggest to do a fresh installation of discotoolkit in a new environment and check if the error still persists.

Notice that we also provide google colab extension in the tutorial website which is install using only pip. Please try that as well.

Thanks and with regards,

Rom Uddamvathanak

**Comment by uddamvathanak** [comment]
I recommend to reinstall as well if the latest version is not install as there might be dependency conflict with other package.

**Comment by Dacy34** [comment]
Hi Uddamvathanak,

Thank you for your reply! I have reinstalled version 1.0.8, and it works fine now! Thanks again!

Best,

Mengtian

**Comment by uddamvathanak** [comment]
Hi Mengtian,

Glad it work for you! We will release additional function soon and thank you for the support!!!

Warm regards,

Rom Uddamvathanak
