### ISSUE TITLE
如何获取基因名称对应的ensembl_id

### ISSUE THREAD

**Issue by dylenchang** [JinmiaoChenLab/DISCOtoolkit_py#3]
非常感谢你们的工作, 想问一下是否有一份文件描述数据集中基因名称和ensembl_id的对应关系? 或者提供一下方法, 再次感谢.

**Comment by lmw123** [comment]
您可以通过https://github.com/JinmiaoChenLab/DISCO_learning/blob/main/ensemble_to_gene_symbol.txt 获得ensemble_id和gene symbol的对应关系，谢谢

best,
Mengwei
